# Generated by Django 3.2 on 2021-05-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210107_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Book_author_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Book_price',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
